import { Iproduct } from "./iproduct";

export let productsList:Iproduct[] = [
    {
        id:1,
        Name:"book",
        price:250,
        quantity:5
    },
    {
        id:2,
        Name:"pen",
        price:50,
        quantity:7
    },
    {
        id:3,
        Name:"disk",
        price:1250,
        quantity:3
    },
    {
        id:4,
        Name:"labtob",
        price:2250,
        quantity:10
    },
    {
        id:5,
        Name:"Notebook",
        price:25,
        quantity:10
    },
    {
        id:6,
        Name:"flower",
        price:12,
        quantity:4
    },
]